### ISSUE TITLE
error while evaluating conditional (k3s_check_cgroup_option.rc == 0): 'dict object' has no attribute 'rc'"

### ISSUE THREAD

**Issue by gloomytrousers** [PyratLabs/ansible-role-k3s#111]
### Summary

The task `xanmanning.k3s : Fail if memory cgroup is not enabled` fails with `"fatal: [pi1.example.com]: FAILED! => {"msg": "The conditional check 'k3s_check_cgroup_option.rc == 0' failed. The error was: error while evaluating conditional (k3s_check_cgroup_option.rc == 0): 'dict object' has no attribute 'rc'"}`

This was OK on 2.7.1 but occurrend when I upgraded to 2.8.2.

I'm on Fedora 33, ansible 2.9.18. The targets are RPi4s (64-bit Raspberry Pi OS).

### Issue Type

- Bug Report

### Controller Environment and Configuration

```text
TASK [xanmanning.k3s : Fail if memory cgroup is not enabled] **********************************************************************************
fatal: [pi1.example.com]: FAILED! => {"msg": "The conditional check 'k3s_check_cgroup_option.rc == 0' failed. The error was: error while evaluating conditional (k3s_check_cgroup_option.rc == 0): 'dict object' has no attribute 'rc'"}
fatal: [pi2.example.com]: FAILED! => {"msg": "The conditional check 'k3s_check_cgroup_option.rc == 0' failed. The error was: error while evaluating conditional (k3s_check_cgroup_option.rc == 0): 'dict object' has no attribute 'rc'"}
fatal: [pi3.example.com]: FAILED! => {"msg": "The conditional check 'k3s_check_cgroup_option.rc == 0' failed. The error was: error while evaluating conditional (k3s_check_cgroup_option.rc == 0): 'dict object' has no attribute 'rc'"}
```

### Steps to Reproduce

Unsure how to reproduce minimally - this is early on in the role so it's something fundamental, but I don't know what it means.

### Expected Result

Playbook should run as expected

### Actual Result

As above.

**Comment by xanmanning** [comment]
Hi. I missed off `check_mode: false` from these checks. It should be fixed in v2.8.3

**Comment by gloomytrousers** [comment]
Thanks for the speedy response, works fine on 2.8.3 :-)

**Comment by gloomytrousers** [comment]
Thanks for the speedy response, works fine on 2.8.3 :-)
